//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalonProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Price { get; set; }
        public string GosNumber { get; set; }
        public string YearRelease { get; set; }
    }
}
